#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'system',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/system',
   :ref => 'master'

cookbook 'rightscale',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/rightscale',
   :ref => 'master'

cookbook 'resolver',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/resolver',
   :ref => 'master'

cookbook 'git',
   :git => 'https://github.com/opscode-cookbooks/git',
   :ref => 'master'

cookbook 'subversion',
   :git => 'https://github.com/opscode-cookbooks/subversion',
   :ref => 'master'
            
cookbook 'cron',
   :git => 'https://github.com/opscode-cookbooks/cron',
   :ref => 'master'

cookbook 'ntp',
   :git => 'https://github.com/opscode-cookbooks/ntp',
   :ref => 'master'

cookbook 'sudo',
   :git => 'https://github.com/opscode-cookbooks/sudo',
   :ref => 'master'

cookbook 'apache2',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/apache2',
   :ref => 'master'

cookbook 'mysql',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/mysql',
   :ref => 'master'

cookbook 'application',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/application',
   :ref => 'master'
   
cookbook 'application_php',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/application_php',
   :ref => 'master'

cookbook 'phpmyadmin_application',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/phpmyadmin_application',
   :ref => 'master'