Vagrant::Config.run do |config|

  config.vm.box = "phpmyadmin"

  config.vm.provision :shell, :inline => 'sed -i "s/#prepend domain-name-servers 127.0.0.1/prepend domain-name-servers 8.8.8.8/g" /etc/dhcp/dhclient.conf && service networking start; gem list | grep chef || gem install chef --no-rdoc --no-ri; apt-get -y update'

  config.vm.forward_port 80, 8888

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug
    chef.json.merge!(JSON.parse(File.read(File.join(Dir.pwd, '..', 'examples', 'chef-solo', 'node.json'))))
    chef.cookbooks_path = File.join(Dir.pwd, '..', 'cookbooks')
    chef.run_list = [ "recipe[rightscale]", "recipe[system]", "recipe[resolver]" ]

  end
end	